### ISSUE TITLE
画像ファイルは静的ファイル用の場所に配置する

### ISSUE THREAD

**Issue by cocoatomo** [syobochim/doc#9]
`conf.py` に `html_static_path = ['_static']` という設定があるので、 `source/_static` 以下に配置するのが良い。

**Comment by cocoatomo** [comment]
この方針が良いのか不安になってきたので調査中です.

**Comment by cocoatomo** [comment]
画像ファイルの置き場所は
- .rst ファイルと同じディレクトリ
- _static ディレクトリ以下

など何種類かのパターンがあり, 特に標準的なものは決まっていない.

文書内で統一されていれば問題無いと考え, このチケットは取り下げる.

**Comment by syobochim** [comment]
ありがとうございます！  
静的ファイルはstaticフォルダ内っていう考え方をしれてハッピーです！
